name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.5
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-5.2"
          - ruby: 2.5
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.0"
          - ruby: 2.5
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.1"
          - ruby: 2.6
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-5.2"
          - ruby: 2.6
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.0"
          - ruby: 2.6
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.1"
          - ruby: 2.7
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.0"
          - ruby: 2.7
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.1"
          - ruby: 2.7
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-7.0"
          - ruby: '3.0'
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-6.1"
          - ruby: '3.0'
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-7.0"
          - ruby: '3.1'
            os: ubuntu-latest
            gemfile: "gemfiles/Gemfile-rails-7.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/bundle
          key: bundle-use-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          gem install bundler -v 2.2.24
          bundle config path /home/runner/bundle
          bundle config --global gemfile ${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake
